### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by JNU-luyi** [justsmart/DIMC#1]
您好 请问您的网络适合的输入是什么（bs,dim,len）维度可以用吗

**Comment by justsmart** [comment]
输入是一个列表，其内容是每个视图的tensor数据，纬度为[bs dim]
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月13日 15:19 |
| 收件人 | justsmart/DIMC ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [justsmart/DIMC] 您好 (Issue #1) |

您好 请问您的网络适合的输入是什么（bs,dim,len）维度可以用吗
